services:
    styrobot:
        build: .
        volumes:
            - ./persist/:/tmp/persist/
            - ./secrets/:/tmp/secrets/
            - ./styrobot/:/app/styrobot/
        restart: unless-stopped
        command: bash -c "cd /app/ && python3 -m styrobot staging"
